### ISSUE TITLE
Missing variable from model file

### ISSUE THREAD

**Issue by james34602** [dr-costas/mad-twinnet#10]
I got errors when loading RNNEnc model:
RuntimeError: Error(s) in loading state_dict for RNNEnc:
        Missing key(s) in state_dict: "gru_enc.weight_ih_l0", "gru_enc.weight_hh_l0", "gru_enc.bias_ih_l0", "gru_enc.bias_hh_l0", "gru_enc.weight_ih_l0_reverse", "gru_enc.weight_hh_l0_reverse", "gru_enc.bias_ih_l0_reverse", "gru_enc.bias_hh_l0_reverse".
        Unexpected key(s) in state_dict: "gru_enc_f.weight_ih", "gru_enc_f.weight_hh", "gru_enc_f.bias_ih", "gru_enc_f.bias_hh", "gru_enc_b.weight_ih", "gru_enc_b.weight_hh", "gru_enc_b.bias_ih", "gru_enc_b.bias_hh".

Got errors when loading RNNDec model:
RuntimeError: Error(s) in loading state_dict for RNNDec:
        Missing key(s) in state_dict: "gru_dec.weight_ih_l0", "gru_dec.weight_hh_l0", "gru_dec.bias_ih_l0", "gru_dec.bias_hh_l0".
        Unexpected key(s) in state_dict: "gru_dec.weight_ih", "gru_dec.weight_hh", "gru_dec.bias_ih", "gru_dec.bias_hh".

But no error had found when loading FNNMasker and FNNDenoiser model

**Comment by dr-costas** [comment]
Hi,

If you want to use the pre-trained weights, please use the version of the code that can reproduce the results of the paper. 

This version is here: https://github.com/dr-costas/mad-twinnet/tree/Paper-code

--Kostas

**Comment by james34602** [comment]
I download Tags Paper-code and get the pre-trained weights from https://zenodo.org/record/1164592#.XOy2nY9-WUk
Still getting the same error.

However. the model is valid when I download this repository using following commit:
https://github.com/dr-costas/mad-twinnet/commit/9f5914c643171ecf88cbd110dfe92f577e353e19

**Comment by dr-costas** [comment]
True. Sorry for that. 

I’m currently away fro office. I will fix it in around 10 days. 

--Kostas

**Comment by dr-costas** [comment]
Hi

I started working on this and it seems that I will create a release of the code at the point were the code at github reflected exactly the code used for the paper. 

If you do not want to wait for me creating this release, you can grab the code from: 

https://github.com/dr-costas/mad-twinnet/tree/70d514fa09bfaf00eb556af6aabbea4b69e44747

Let me know if this worked for you.

**Comment by dr-costas** [comment]
The release is ready: 

https://github.com/dr-costas/mad-twinnet/releases/tag/Paper-code

**Comment by dr-costas** [comment]
Dear @james34602 

Is the issue solved for you now?

**Comment by james34602** [comment]
Yes, I think.

**Comment by dr-costas** [comment]
Great!

I will close this issue and if you have any other problem, please create an issue :) 

Thnx!
