### ISSUE TITLE
'outputs/states/mad.pt' file not found error while using the use_me.py script

### ISSUE THREAD

**Issue by snnithya** [dr-costas/mad-twinnet#14]
Hi, I am trying to use the MaD TwinNet pre-trained model on an audio sample with the use_me.py script. I have downloaded the pretrained weights from here (https://zenodo.org/record/1164592#.X-CFxNbhXeQ) as suggested in the ReadMe file and placed them in the outputs/states directory. However there doesn't seem to be a mad.pt file present which seems to be causing the error. Please let me know how this can be fixed?

Thanks

**Comment by dr-costas** [comment]
Hey! 

Thank you for checking our code! Just to be sure, have you use the release that reproduces the results of the paper, or the master branch? 

You can find the release at: https://github.com/dr-costas/mad-twinnet/releases/tag/Paper-code

**Comment by snnithya** [comment]
Hi,

Thanks for replying. I was using the code from the master branch. It works fine with the other version! 

Thanks
Nithya

**Comment by dr-costas** [comment]
Super! I’m that it worked!
