### ISSUE TITLE
output size not equal to input size

### ISSUE THREAD

**Issue by ghost** [dr-costas/mad-twinnet#4]
My input time-domain mixture mono signal is of a certain length, but the output voice and background music files are equal, but not equal to the input file. Is there an easy fix for this?

**Comment by dr-costas** [comment]
Hi, 

The function `data_process_results_testing` in `helpers.data_feeder` does what you looking for. Please check it and let me know.

**Comment by ghost** [comment]
I am looking at it, but not exactly sure if I understand what to do with that. Please help me. Thanks!

**Comment by dr-costas** [comment]
You will have to check the function, see what it does, check which of the files are longer. 

I will have to have more information to help you.
