### ISSUE TITLE
Error When I run scripts/training.py

### ISSUE THREAD

**Issue by ghost** [dr-costas/mad-twinnet#6]
Hello !
I'm getting error when I run training.py and I couldn't know why? 

```
-- Starting training process. Debug mode: False
-- Setting up modules... done.
-- Setting up optimizes and losses... done.
-- Training starts

Traceback (most recent call last):
  File "scripts/training.py", line 199, in <module>
    main()
  File "scripts/training.py", line 195, in main
    training_process()
  File "scripts/training.py", line 176, in training_process
    l_m=torch.mean(torch.FloatTensor(epoch_l_m)),
RuntimeError: invalid argument 1: empty Tensor at /pytorch/torch/lib/TH/generic/THTensorMath.c:3311
```
Thank You!

**Comment by dr-costas** [comment]
Hi! 

It seems that there are no values produced for the loss of the Masker, during training. 

Let me check it on Tuesday and I will post here again.

**Comment by dr-costas** [comment]
Also, could you please tell me which version of PyTorch are you using?

**Comment by ghost** [comment]
Thank you for fast reply !

I'm using python 3.6

**Comment by dr-costas** [comment]
Version of PyTorch? Not version of Python.

**Comment by ghost** [comment]
Oh ! sorry my bad .. the version 0.3.0.post4

**Comment by dr-costas** [comment]
Hi

I could not reproduce your error. Seeing from your error message that you posted, the variable `epoch_l_m` (the epoch loss for the masker) is empty, that is why your get "empty Tensor" error. 

I would suggest to see if your python path is setup properly (according to the guidelines given in the README file). 

Please check your python path for the project and make sure that you are using the `export PYTHONPATH...` part, given in the README file.

**Comment by ghost** [comment]
Hi!

Last couple days I tried my best to find from where this error is coming
from. I did exactly what in Readme file and the extracting is working
normally but the error happens only when I try to train?
I setup Dataset DSD100 with couple songs.
What do you think ?

Thank you so much
Best,

**Comment by dr-costas** [comment]
I would suggest you to do debug. I cannot figure out why you have this problem. 

If you could get a breakpoint at the line where the values are appended at the `epoch_l_m` list, and see what values are appended.

**Comment by ghost** [comment]
Thank you so much for 
I think that the problem can be Dataset set-up
My Dataset DSD100 folder looks like default structure
my problem is that I don't know which files should I rename them to numbers and I don't understand this line "each file name should have an identifier whether the file is about the mixture, the voice, the bass, and other." it means like  001(the bass).wav ?
so could you please help me.

Best regards,

**Comment by dr-costas** [comment]
Hi, 

Sorry for the not clear enough description on how the naming conventions of the dataset are. 

- The mixture files should be named as "mixture.wav"
- The voice files should be names as "vocals.wav"
- The bass files as "bass.wav"
- The drums as "drums.wav"
- The other as "other.wav". 

Do the above help a bit?

Cheers!

**Comment by ghost** [comment]
Oh thank you so much !

It looks same as the default in DSD100.
I removed the lines in the training.py file where the error is coming from
!
I think now its start to work and i can see result in audio files folder do
you think this can be effective?

Thank you

**Comment by dr-costas** [comment]
I have not understood what exactly you are trying to do. The line that you removed was calculating the mean loss of the masker for one epoch. 

I would guess that now you do not get any indication for the losses in one epoch?

**Comment by ghost** [comment]
Yes ! That's true I'm not getting any indication.
I thought that those lines are for showing what happens during the training
and they don't have a relation with the progress.
I'm still looking for any solution!  Anything new to resolve this issue??


I have not understood what exactly you are trying to do. The line that you

**Comment by ghost** [comment]
Hi ! 

Is there any update about this issue? I'm having the same problem even I'm trying my best to resolve it.
by the way I'm using the CPU version of Torch, do you think it can be the reason?

```
-- Starting training process. Debug mode: False
-- Setting up modules... done.
-- Setting up optimizes and losses... done.
-- Training starts

Traceback (most recent call last):
  File "scripts/training.py", line 199, in <module>
    main()
  File "scripts/training.py", line 195, in main
    training_process()
  File "scripts/training.py", line 176, in training_process
    l_m=torch.mean(torch.FloatTensor(epoch_l_m)),
RuntimeError: invalid argument 1: empty Tensor at /pytorch/torch/lib/TH/generic/THTensorMath.c:3311
```
Thank you in advance.

**Comment by dr-costas** [comment]
Hey,

I tried to reproduce your error but I cannot. 

If you want, we can try together and solve your problem. What I would do, is to put a break point at line  166 of `training.py`

`
epoch_l_m.append(l_m.data[0])
`

and see what the value of `l_m.data`. 

Could you please tell me the above? 

Cheers and thank you for trying to solve this with me :)

**Comment by ghost** [comment]
Hello ! 

Thank you so much ! I think I found the solution for that.
In '  settings.py ' I changed the files_per_pass value from 4 to 2 and it starts working normally.
maybe because I'm using the small DSD100 dataset '120MB' for test (even I tested before with full DSD100 dataset)? 
Do you have any explanation for that?

```
# Process constants
training_constants = {
    'epochs': 2 if debug else 100,
    'batch_size': 16,
    'files_per_pass': 2
}
```
Thank you so much

**Comment by dr-costas** [comment]
Hi! 

I'm very glad that finally worked for you. 

The only explanation that I can think of now is due to some rounding in divisions. That is, with the number of files that you had, the division with the `files_per_pass` gave some invalid numbers and this resulted in not getting files, thus not giving output for the `l_m`, and this resulting to the empty list of `epoch_l_m`. 

The above is just a speculation though. I would have to dig a bit more to this particular report. Since I'm planning to update the code for Python 3.X and PyTorch 0.4.X, I think that I will do it but for the new version :)

In any case, thank you so much for reporting this and staying here with me to fix it. 

Enjoy using the code!!!
