### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to' when use use_me.py

### ISSUE THREAD

**Issue by lyapple2008** [dr-costas/mad-twinnet#8]
Hi, i wanted to use the pre-trained model to process music. But i got error below when i run use_me.py

`Traceback (most recent call last):
  File "D:/Workspace/MusicVoiceSeparation/OpenSourcs/mad-twinnet-master/scripts/use_me.py", line 192, in <module>
    main()
  File "D:/Workspace/MusicVoiceSeparation/OpenSourcs/mad-twinnet-master/scripts/use_me.py", line 187, in main
    output_file_names=_make_target_file_names(input_list)
  File "D:/Workspace/MusicVoiceSeparation/OpenSourcs/mad-twinnet-master/scripts/use_me.py", line 56, in use_me_process
    rnn_enc.load_state_dict(torch.load(output_states_path['rnn_enc'])).to(device)
AttributeError: 'NoneType' object has no attribute 'to'`

Do you have any idea about that? BTW, i have no gpu in my computer.

**Comment by lyapple2008** [comment]
i had fixed this error.

    rnn_enc.load_state_dict(torch.load(output_states_path['rnn_enc']))
    rnn_enc.to(device)

    rnn_dec.load_state_dict(torch.load(output_states_path['rnn_dec']))
    rnn_dec.to(device)

    fnn.load_state_dict(torch.load(output_states_path['fnn']))
    fnn.to(device)

    denoiser.load_state_dict(torch.load(output_states_path['denoiser']))
    denoiser.to(device)

**Comment by dr-costas** [comment]
Oh! Thnx for noticing this. I will fix it in the code. 

I forgot that the ‘load_state_dict’ does not return something.
