### ISSUE TITLE
in case of single background instrument

### ISSUE THREAD

**Issue by HIN0209** [dr-costas/mad-twinnet#9]
Hello!
I have been trying to train with my dataset having voice and single instrument (e.g. drums). 

In lines 397- of helpers/data_feeder.py, the following appears to require changes. Is it OK to just delete 'bass' and 'others' without adjusting other parts? Your suggestion wound be appreciated.

if not usage_case:
        bass = wav_read(os.path.join(sources_parent_path, 'bass.wav'), mono=False)[0]
        drums = wav_read(os.path.join(sources_parent_path, 'drums.wav'), mono=False)[0]
        others = wav_read(os.path.join(sources_parent_path, 'other.wav'), mono=False)[0]
        voice = wav_read(os.path.join(sources_parent_path, 'vocals.wav'), mono=False)[0]

        bg_true = np.sum(bass + drums + others, axis=-1) * 0.5
        voice_true = np.sum(voice, axis=-1) * 0.5
        mix = np.sum(bass + drums + others + voice, axis=-1) * 0.5

**Comment by dr-costas** [comment]
Hi, 

Sure! Line 403 creates the background component (i.e. the music without the voice) from the available instruments (i.e. bass, drums, others), and line 405 mixes the instruments and the voice. 

If you do not have some of the instruments (e.g. bass or others), then you can safely remove them. 

```python
bg_true = np.sum(bass + drums + others, axis=-1) * 0.5  # Line 403 --> You can remove bass and others
voice_true = np.sum(voice, axis=-1) * 0.5  # Line 404
mix = np.sum(bass + drums + others + voice, axis=-1) * 0.5  # Line 405  --> You can remove bass and others
```

**Comment by HIN0209** [comment]
@dr-costas, Thanks, happy to hear that complex modification is not needed.
